name: ci

on:
  push:
  schedule:
    - cron: '0 15 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: stu2005/libaribb25:latest
      -
        name: Build and push kai ver
        uses: docker/build-push-action@v4
        with:
          dockerfile: Dockerfile.kai
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: stu2005/libaribb25:kai
